// <auto-generated />
using System;
using Fiap.Atividade.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Fiap.Atividade.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240624225057_MigracaoSecundaria")]
    partial class MigracaoSecundaria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fiap.Atividade.Models.CasaModel", b =>
                {
                    b.Property<long>("CasaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CasaId"));

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.HasKey("CasaId");

                    b.HasIndex("Localizacao")
                        .IsUnique();

                    b.ToTable("tbl_casa");
                });

            modelBuilder.Entity("Fiap.Atividade.Models.OcorrenciaModel", b =>
                {
                    b.Property<long>("OcorrenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OcorrenciaId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<DateTime>("DiaOcorrencia")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.HasKey("OcorrenciaId");

                    b.ToTable("tbl_ocorrencia");
                });

            modelBuilder.Entity("Fiap.Atividade.Models.SistemaAlarmeModel", b =>
                {
                    b.Property<long>("SistemaAlarmeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SistemaAlarmeId"));

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)");

                    b.HasKey("SistemaAlarmeId");

                    b.HasIndex("Localizacao")
                        .IsUnique();

                    b.ToTable("tbl_sistema_alarme");
                });
#pragma warning restore 612, 618
        }
    }
}
