name: .NET Core CI Workflow 1.0

on: push

jobs:

  ambient: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Display message - Setting up .NET Core SDK
        run: echo "Configurando .NET Core SDK"

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Display message - Restoring dependencies
        run: echo "Restaurando as dependências do projeto"

      - name: Restore dependencies
        run: dotnet restore 

  build:
    runs-on: ubuntu-latest
    
    steps:
     -  name: Checkout repository
        uses: actions/checkout@v2
      
     -  name: Display message - Setting up .NET Core SDK
        run: echo "Configurando .NET Core SDK"

     -  name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

     -  name: Display message - Restoring dependencies
        run: echo "Restaurando as dependências do projeto"

     -  name: Restore dependencies
        run: dotnet restore 

     -  name: Display message - Building the project
        run: echo "Iniciando a build do projeto"

     -  name: Build
        run: dotnet build --configuration Release --no-restore

     -  name: Display message - Running tests
        run: echo "Build realizado com sucesso. Agora executando os testes."

     -  name: Test
        run: dotnet test --no-restore --verbosity normal

     -  name: Display message - Pipeline completed
        run: echo "Pipeline concluído com sucesso!"

  test:
    runs-on: ubuntu-latest
    
    steps:
     -  name: Checkout repository
        uses: actions/checkout@v2
      
     -  name: Display message - Setting up .NET Core SDK
        run: echo "Configurando .NET Core SDK"

     -  name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

     -  name: Display message - Restoring dependencies
        run: echo "Restaurando as dependências do projeto"

     -  name: Restore dependencies
        run: dotnet restore 

     -  name: Display message - Running tests
        run: echo "Build realizado com sucesso. Agora executando os testes."

     -  name: Test
        run: dotnet test --no-restore --verbosity normal

     -  name: Display message - Pipeline completed
        run: echo "Pipeline concluído com sucesso!"
